#!/bin/bash

export PATH='/usr/local/bin:${PATH}'

status="$(zpool status -x)"
database="/etc/zfs/zpool.status"

if [[ "${status}" == "all pools are healthy" || "${status}" == "no pools available" ]]; then
    # set current state
    echo "healthy=true" > "${database}"
else
    # get known state
    source "${database}"

    if [[ "${healthy}" == "true" ]]; then # state has changed, 'was healthy'
        # `notify` uses pushover to send SMS notifications
        notify "$(zpool status)"
        # set new state
        echo "healthy=false" > "${database}"
    fi
fi
